#!/usr/bin/env bash
# Which formulas should be hanlded by homebrew?

# Extend brew formulas repos
taps=(caskroom/cask
      caskroom/versions
      homebrew/binary
      homebrew/completions
      homebrew/dupes
      homebrew/versions)

# Formula
formulas=(readline
          zlib
          git
          ctags
          pyenv
          rbenv
          ruby-build
          macvim
          node
          nvm
          packer
          gibo
          vagrant-completion
          pip-completion
          packer-completion
          grunt-completion
          gem-completion
          bundler-completion
          bash-completion)

# Cask
casks=(vagrant)

