#!/usr/bin/env bash

# Tap


# Formula
formula readline \
        zlib \
        git \
        ctags \
        pyenv \
        rbenv \
        macvim \
        node \
        nvm

# Cask
cask vagrant

