#!/usr/bin/env bash
# Which formulas should be hanlded by homebrew?

# Extend brew formulas repos
taps=(caskroom/cask
      caskroom/versions
      homebrew/binary
      homebrew/completions
      homebrew/dupes)

# Formula
formulas=(readline
          zlib
          git
          ctags
          pyenv
          rbenv
          macvim
          node
          nvm
          packer
          gibo
          vagrant-completion)

# Cask
casks=(vagrant)

