#!/usr/bin/env bash
# Install ~/.dotfiles

# More strict
set -e
set -u


DOTFILES_LOCAL=~/.dotfiles
DOTFILES_REMOTE="https://github.com/woody/dotfiles.git"

declare IS_DEV

#Parse arguments
for arg in "$@"; do
  case $arg in
    --dev)
      IS_DEV=1
      ;;
  esac
done

# Skip over clone from remote while development.
if [ $IS_DEV ]; then
  DOTFILES_DEV=$(/usr/bin/dirname $0)

  [[ $DOTFILES_DEV == "." ]] && {
    DOTFILES_DEV=$(/bin/pwd)
  }

  $(/usr/bin/which install) -d $DOTFILES_DEV $DOTFILES_LOCAL
else
  [ -e $DOTFILES_LOCAL ] && {
    # Checkout ~/.dotfiles existence
    echo "~/.dotfiles exists, and shouldn't installed again." >&2
    exit
  } || {
    # Clone from repo
    $(/usr/bin/which git) clone --recursive --quite $DOTFILES_REMOTE $DOTFILES_LOCAL
  }
fi
